### ISSUE TITLE
dockerを用いたphpの環境構築

### ISSUE THREAD

**Issue by k911672** [k911672/todo-php-docker#1]

**Comment by k911672** [comment]
## ブラウザ表示について

```
imuranaoki@kimuranaokinoMacBook-Pro todo-php-docker % ls
Readme.md		app			docker			docker-compose.yml
```
appディレクトリ内のファイルがブラウザで表示される。

### ブラウザ表示の理由
- docker-compose.ymlの設定
```
kimuranaoki@kimuranaokinoMacBook-Pro todo-php-docker % cat docker-compose.yml 
version: '3'
services:
  web:
    container_name: nginx-app
    image: nginx:1.15.6
    ports:
      - "8000:80"
    depends_on: 
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    container_name: php-app
    build: ./docker/php
    volumes:
     - .:/var/www/html
    depends_on:
      - mysql
  mysql:
    container_name: mysql-app
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: common
      MYSQL_USER: michael
      MYSQL_PASSWORD: 11922960Kim@
      MYSQL_ROOT_PASSWORD: 11922960Kim@
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
```
appコンテナの
```
    volumes:
     - .:/var/www/html
```
の設定で、カレントディレクトリ内のデータをコンテナ何の/var/www/htmlディレクトリにマウントさせている。
↓実際にコンテナ内を見ると
```
root@672765572b12:/var/www/html# ls
Readme.md  app	docker	docker-compose.yml
```
docker-compose.ymlがあるカレントディレクトリのデータ全て、/var/www/htmlディレクトリ内にある。

- default.confの設定
```
kimuranaoki@kimuranaokinoMacBook-Pro web % cat default.conf 
server {
    listen 80;

    root  /var/www/html/app;
    index index.php index.html index.htm;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass   app:9000;
          fastcgi_index  index.php;

          include        fastcgi_params;
          fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param  PATH_INFO $fastcgi_path_info;
      }
}
```
rootで参照するファイルのパスを記述している。
この記述より、/var/www/html/appディレクトリ内のファイルとブラウザを繋げている。
